### ISSUE TITLE
Webui is spamming server with thousands of websocket requests

### ISSUE THREAD

**Issue by t46g** [USA-RedDragon/DMRHub#138]
Hi,
I have installed the newst Version of DMRHub with docker and had a problem when websocket request are spammed to the server which caused also chrome to freeze after some time. I solved it by configuring the CORS_HOSTS correctly.
But I would appreaciate it, when the retrying of establishing a websocket connection will be paused after some amount of errors or the number of requests will be reduced. After a few seconds I had in my google chrome log several ten of thousands error entries.

**Comment by USA-RedDragon** [comment]
Hey, thanks for the feedback. I'll add something to exponentially backoff on websocket disconnections/failed connections to v1.0.18 tonight
