### ISSUE TITLE
Error on docker run "exec /DMRHub: exec format error"

### ISSUE THREAD

**Issue by t46g** [USA-RedDragon/DMRHub#147]
On some of the new docker image versions including the latest 1.0.18 there seems to be a problem with the docker entrypoint. On startup only this error appears in the log and then the container shuts down immediately:
exec /DMRHub: exec format error

**Comment by t46g** [comment]
I have the presumption that the error was introduced in commit 63a1d7749ef6ef843f39b1f1f42957840c200a29 by changing the line
`COPY --from=builder /DMRHub/bin/DMRHub /DMRHub`
to
`COPY DMRHub /`
because the entrypoint is still pointing to "/DMRHub"

**Comment by USA-RedDragon** [comment]
Was this from GHCR or Docker Hub? Which architecture? I had a double check of the `:latest` and `:v1.0.18` on x86_64 and it seems the binaries are appropriately starting.

**Comment by t46g** [comment]
I am using the amd-64 version from GHCR. If I can test anything or do you need any informations, please let me know.

**Comment by USA-RedDragon** [comment]
I've tried to reproduce this, but I haven't been able to. 

Can you send me your `docker run` command and the output of `docker info`? Double-check there's no sensitive info in `docker info` output (I don't think there is though) and strip it out if needed.

I released v1.0.19 today which pushed new images up to GHCR and Docker Hub. It's possible that could have fixed it too,

**Comment by USA-RedDragon** [comment]
Ah, I see. unRAID. 

I was able to reproduce the issue on unRAID, I'll dig deeper into it.
